@url = http://localhost:5000
@parkingSpotId = 7711ff63-afab-4ae6-ad71-09f2afafa60f

###
GET {{url}}

###
GET {{url}}/parking-spots

###
GET {{url}}/parking-spots/{{parkingSpotId}}

###
POST {{url}}/parking-spots
Content-Type: application/json

{
    "name": "P1"
}


###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations
Content-Type: application/json

{
    "licensePlate": "ABC123",
    "date": "2022-05-17"
}