@url = http://localhost:5000
@parkingSpotId = dcffe0a8-061b-4f66-aa7a-883023edb632

###
GET {{url}}

###
GET {{url}}/parking-spots

###
GET {{url}}/parking-spots/{{parkingSpotId}}

###
GET {{url}}/api/parking-spots/{{parkingSpotId}}

###
POST {{url}}/parking-spots
Content-Type: application/json

{
    "name": "P1"
}

###
POST {{url}}/api/parking-spots
Content-Type: application/json

{
    "name": "P1"
}


###
POST {{url}}/parking-spots/{{parkingSpotId}}/reservations
Content-Type: application/json

{
    "licensePlate": "ABC123",
    "date": "2022-05-17"
}